kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-go
  labels:
    app: my-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-go
  template:
    metadata:
      labels:
        app: my-go
    spec:
      containers:
        - name: my-go
          image: quay.io/appsvcrhtap/goapp:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-go-svc
spec:
ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
selector:
  app: my-go
---
apiVersion: primaza.io/v1alpha1
kind: ServiceClaim
metadata:
  name: my-app-dummy-for-appns
spec:
  serviceClassIdentity:
  - name: type
    value: dummy
  - name: scope
    value: claim-for-appns
  serviceEndpointDefinitionKeys:
  - url
  - password
  applicationClusterContext:
    clusterEnvironmentName: worker
    namespace: applications
  application:
    kind: Deployment
    apiVersion: apps/v1
    selector:
      matchLabels:
        app: my-go
